import type { NewsArticle, CalendarEvent } from '@/stores/news-store'

// Helper to generate dates
function daysAgo(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() - days)
  return date.toISOString()
}

function hoursAgo(hours: number): string {
  const date = new Date()
  date.setHours(date.getHours() - hours)
  return date.toISOString()
}

function daysFromNow(days: number): string {
  const date = new Date()
  date.setDate(date.getDate() + days)
  return date.toISOString()
}

// Mock News Articles
export const mockNewsArticles: NewsArticle[] = [
  {
    id: 'news-001',
    title: 'VN-Index vượt 1.300 điểm, thanh khoản đạt kỷ lục 32.000 tỷ đồng',
    summary: 'Thị trường chứng khoán Việt Nam tiếp tục bùng nổ với chỉ số VN-Index vượt mốc 1.300 điểm lần đầu tiên kể từ đầu năm. Thanh khoản toàn thị trường đạt mức kỷ lục 32.000 tỷ đồng.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=400',
    category: 'market',
    relatedSymbols: ['VNM', 'FPT', 'VCB'],
    publishedAt: hoursAgo(1),
  },
  {
    id: 'news-002',
    title: 'FPT công bố KQKD Q4/2024: Lợi nhuận tăng 25% so với cùng kỳ',
    summary: 'Tập đoàn FPT vừa công bố kết quả kinh doanh quý 4/2024 với doanh thu đạt 15.200 tỷ đồng và lợi nhuận sau thuế tăng 25% so với cùng kỳ năm trước.',
    source: 'VnExpress',
    sourceUrl: 'https://vnexpress.net',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=400',
    category: 'company',
    relatedSymbols: ['FPT'],
    publishedAt: hoursAgo(2),
  },
  {
    id: 'news-003',
    title: 'Fed giữ nguyên lãi suất, thị trường toàn cầu phản ứng tích cực',
    summary: 'Cục Dự trữ Liên bang Mỹ (Fed) quyết định giữ nguyên lãi suất ở mức 5.25-5.5%, phát tín hiệu có thể cắt giảm lãi suất trong năm 2025.',
    source: 'Reuters',
    sourceUrl: 'https://reuters.com',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=400',
    category: 'macro',
    relatedSymbols: [],
    publishedAt: hoursAgo(3),
  },
  {
    id: 'news-004',
    title: 'Bitcoin vượt $100,000, kéo theo nhóm cổ phiếu crypto Việt tăng mạnh',
    summary: 'Bitcoin đã chính thức vượt mốc $100,000 lần đầu tiên trong lịch sử. Tại Việt Nam, các cổ phiếu liên quan đến blockchain như ABC tăng trần.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?w=400',
    category: 'crypto',
    relatedSymbols: [],
    publishedAt: hoursAgo(4),
  },
  {
    id: 'news-005',
    title: 'Vingroup ra mắt đại dự án Vinhomes Global Gate tại Hà Nội',
    summary: 'Tập đoàn Vingroup chính thức giới thiệu dự án Vinhomes Global Gate với quy mô 300 ha, tổng vốn đầu tư dự kiến 5 tỷ USD.',
    source: 'Vietstock',
    sourceUrl: 'https://vietstock.vn',
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=400',
    category: 'company',
    relatedSymbols: ['VIC', 'VHM'],
    publishedAt: hoursAgo(5),
  },
  {
    id: 'news-006',
    title: 'Ngân hàng ACB được nâng hạn mức tăng trưởng tín dụng lên 18%',
    summary: 'Ngân hàng Nhà nước vừa phê duyệt nâng room tín dụng cho ACB từ 14% lên 18%, tạo điều kiện cho ngân hàng mở rộng cho vay trong quý cuối năm.',
    source: 'VnExpress',
    sourceUrl: 'https://vnexpress.net',
    imageUrl: 'https://images.unsplash.com/photo-1541354329998-f4d9a9f9297f?w=400',
    category: 'company',
    relatedSymbols: ['ACB'],
    publishedAt: hoursAgo(6),
  },
  {
    id: 'news-007',
    title: 'Giá thép thế giới giảm mạnh, HPG lao dốc 5%',
    summary: 'Giá thép cuộn cán nóng tại Trung Quốc giảm về mức thấp nhất trong 3 năm, gây áp lực lên cổ phiếu Hòa Phát và các doanh nghiệp thép Việt.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400',
    category: 'company',
    relatedSymbols: ['HPG', 'HSG', 'NKG'],
    publishedAt: hoursAgo(8),
  },
  {
    id: 'news-008',
    title: 'Thặng dư thương mại Việt Nam đạt kỷ lục 28 tỷ USD năm 2024',
    summary: 'Theo Tổng cục Hải quan, xuất siêu của Việt Nam trong năm 2024 ước đạt 28 tỷ USD, cao nhất từ trước đến nay.',
    source: 'VnExpress',
    sourceUrl: 'https://vnexpress.net',
    imageUrl: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=400',
    category: 'macro',
    relatedSymbols: [],
    publishedAt: hoursAgo(10),
  },
  {
    id: 'news-009',
    title: 'Thế Giới Di Động đóng cửa thêm 150 cửa hàng để tái cấu trúc',
    summary: 'MWG tiếp tục chiến lược tối ưu hóa mạng lưới, dự kiến đóng thêm 150 cửa hàng không hiệu quả trong quý 1/2025.',
    source: 'Vietstock',
    sourceUrl: 'https://vietstock.vn',
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=400',
    category: 'company',
    relatedSymbols: ['MWG'],
    publishedAt: hoursAgo(12),
  },
  {
    id: 'news-010',
    title: 'Nhà đầu tư nước ngoài mua ròng 2.000 tỷ đồng trong tuần',
    summary: 'Khối ngoại quay trở lại mua ròng mạnh mẽ trên sàn HOSE, tập trung vào các bluechip như VNM, FPT, VCB.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=400',
    category: 'market',
    relatedSymbols: ['VNM', 'FPT', 'VCB'],
    publishedAt: daysAgo(1),
  },
  {
    id: 'news-011',
    title: 'Techcombank báo lãi kỷ lục, cổ phiếu TCB tăng 8%',
    summary: 'Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank) công bố lợi nhuận năm 2024 đạt 27.000 tỷ đồng, tăng 35% so với năm trước.',
    source: 'Bloomberg',
    sourceUrl: 'https://bloomberg.com',
    imageUrl: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=400',
    category: 'company',
    relatedSymbols: ['TCB'],
    publishedAt: daysAgo(1),
  },
  {
    id: 'news-012',
    title: 'Trung Quốc công bố gói kích thích kinh tế 2.000 tỷ NDT',
    summary: 'Chính phủ Trung Quốc thông qua gói kích thích kinh tế lớn nhất trong 5 năm, tạo động lực cho thị trường châu Á.',
    source: 'Reuters',
    sourceUrl: 'https://reuters.com',
    imageUrl: 'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=400',
    category: 'international',
    relatedSymbols: [],
    publishedAt: daysAgo(1),
  },
  {
    id: 'news-013',
    title: 'Vinamilk ký hợp đồng xuất khẩu 500 triệu USD sang Trung Đông',
    summary: 'CTCP Sữa Việt Nam (Vinamilk) vừa ký kết hợp đồng xuất khẩu sữa và các sản phẩm từ sữa trị giá 500 triệu USD với đối tác UAE.',
    source: 'VnExpress',
    sourceUrl: 'https://vnexpress.net',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
    category: 'company',
    relatedSymbols: ['VNM'],
    publishedAt: daysAgo(2),
  },
  {
    id: 'news-014',
    title: 'Lạm phát tháng 12 tăng nhẹ 0.2%, cả năm ở mức 3.5%',
    summary: 'Theo Tổng cục Thống kê, chỉ số giá tiêu dùng (CPI) tháng 12 tăng 0.2% so với tháng trước, đưa lạm phát cả năm 2024 về mức 3.5%.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=400',
    category: 'macro',
    relatedSymbols: [],
    publishedAt: daysAgo(2),
  },
  {
    id: 'news-015',
    title: 'VinFast giao 50.000 xe điện trong năm 2024',
    summary: 'VinFast công bố đã giao thành công 50.000 xe điện trong năm 2024, tăng gấp đôi so với năm trước.',
    source: 'Vietstock',
    sourceUrl: 'https://vietstock.vn',
    imageUrl: 'https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=400',
    category: 'company',
    relatedSymbols: ['VIC'],
    publishedAt: daysAgo(2),
  },
  {
    id: 'news-016',
    title: 'Ethereum 2.0 hoàn tất nâng cấp, phí giao dịch giảm 90%',
    summary: 'Mạng lưới Ethereum đã hoàn tất bản nâng cấp lớn nhất trong năm, giảm phí gas xuống mức thấp kỷ lục.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=400',
    category: 'crypto',
    relatedSymbols: [],
    publishedAt: daysAgo(3),
  },
  {
    id: 'news-017',
    title: 'Masan hoàn tất mua lại chuỗi WinMart từ Vingroup',
    summary: 'Tập đoàn Masan chính thức sở hữu 100% chuỗi siêu thị WinMart sau khi mua lại toàn bộ phần vốn còn lại từ Vingroup.',
    source: 'Bloomberg',
    sourceUrl: 'https://bloomberg.com',
    imageUrl: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=400',
    category: 'company',
    relatedSymbols: ['MSN', 'VIC'],
    publishedAt: daysAgo(3),
  },
  {
    id: 'news-018',
    title: 'Nhật Bản nâng lãi suất lần đầu sau 17 năm',
    summary: 'Ngân hàng Trung ương Nhật Bản (BOJ) bất ngờ nâng lãi suất từ -0.1% lên 0.1%, chấm dứt kỷ nguyên lãi suất âm.',
    source: 'Reuters',
    sourceUrl: 'https://reuters.com',
    imageUrl: 'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=400',
    category: 'international',
    relatedSymbols: [],
    publishedAt: daysAgo(3),
  },
  {
    id: 'news-019',
    title: 'SSI dẫn đầu thị phần môi giới chứng khoán quý 4/2024',
    summary: 'Công ty CP Chứng khoán SSI tiếp tục giữ vững vị trí số 1 về thị phần môi giới trên sàn HOSE với 12.5%.',
    source: 'Vietstock',
    sourceUrl: 'https://vietstock.vn',
    imageUrl: 'https://images.unsplash.com/photo-1642790551116-18e150f248e5?w=400',
    category: 'company',
    relatedSymbols: ['SSI'],
    publishedAt: daysAgo(4),
  },
  {
    id: 'news-020',
    title: 'Chỉ số VN30 Futures thiết lập mức cao mới',
    summary: 'Hợp đồng tương lai VN30 đã vượt qua mức 1.350 điểm, thiết lập kỷ lục mới kể từ khi ra mắt năm 2017.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1535320903710-d993d3d77d29?w=400',
    category: 'market',
    relatedSymbols: [],
    publishedAt: daysAgo(4),
  },
  {
    id: 'news-021',
    title: 'GDP Việt Nam năm 2024 tăng 7.1%, vượt mục tiêu',
    summary: 'Tổng sản phẩm quốc nội (GDP) Việt Nam năm 2024 ước tính tăng 7.1%, cao hơn mục tiêu 6-6.5% đề ra.',
    source: 'VnExpress',
    sourceUrl: 'https://vnexpress.net',
    imageUrl: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=400',
    category: 'macro',
    relatedSymbols: [],
    publishedAt: daysAgo(5),
  },
  {
    id: 'news-022',
    title: 'Vietcombank được chấp thuận tăng vốn điều lệ lên 80.000 tỷ',
    summary: 'Ngân hàng Nhà nước đã chấp thuận đề án tăng vốn điều lệ của Vietcombank từ 55.000 tỷ lên 80.000 tỷ đồng.',
    source: 'Bloomberg',
    sourceUrl: 'https://bloomberg.com',
    imageUrl: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?w=400',
    category: 'company',
    relatedSymbols: ['VCB'],
    publishedAt: daysAgo(5),
  },
  {
    id: 'news-023',
    title: 'Solana vượt Ethereum về khối lượng giao dịch DeFi',
    summary: 'Lần đầu tiên trong lịch sử, Solana vượt qua Ethereum về tổng khối lượng giao dịch trên các ứng dụng DeFi.',
    source: 'CafeF',
    sourceUrl: 'https://cafef.vn',
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=400',
    category: 'crypto',
    relatedSymbols: [],
    publishedAt: daysAgo(6),
  },
  {
    id: 'news-024',
    title: 'Novaland hoàn tất tái cấu trúc nợ 2 tỷ USD',
    summary: 'CTCP Tập đoàn Đầu tư Địa ốc No Va (Novaland) đã hoàn tất đàm phán tái cấu trúc khoản nợ 2 tỷ USD với các chủ nợ.',
    source: 'Vietstock',
    sourceUrl: 'https://vietstock.vn',
    imageUrl: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=400',
    category: 'company',
    relatedSymbols: ['NVL'],
    publishedAt: daysAgo(6),
  },
  {
    id: 'news-025',
    title: 'Thị trường IPO Việt Nam sôi động trở lại với 15 thương vụ',
    summary: 'Năm 2024 ghi nhận 15 thương vụ IPO mới trên các sàn chứng khoán Việt Nam, tổng giá trị huy động 2.5 tỷ USD.',
    source: 'Reuters',
    sourceUrl: 'https://reuters.com',
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400',
    category: 'market',
    relatedSymbols: [],
    publishedAt: daysAgo(7),
  },
]

// Mock Calendar Events
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'event-001',
    title: 'KQKD Q4/2024 - FPT',
    type: 'earnings',
    date: daysFromNow(2),
    time: '17:00',
    impact: 'high',
    relatedSymbols: ['FPT'],
    description: 'Công bố kết quả kinh doanh quý 4 năm 2024',
  },
  {
    id: 'event-002',
    title: 'Họp Fed tháng 1/2025',
    type: 'economic',
    date: daysFromNow(5),
    time: '02:00',
    impact: 'high',
    relatedSymbols: [],
    description: 'Cuộc họp chính sách tiền tệ của Fed',
  },
  {
    id: 'event-003',
    title: 'Trả cổ tức VCB - 1,500đ/cp',
    type: 'dividend',
    date: daysFromNow(7),
    impact: 'medium',
    relatedSymbols: ['VCB'],
    description: 'Ngày thanh toán cổ tức tiền mặt',
  },
  {
    id: 'event-004',
    title: 'KQKD Q4/2024 - VNM',
    type: 'earnings',
    date: daysFromNow(8),
    time: '16:30',
    impact: 'high',
    relatedSymbols: ['VNM'],
    description: 'Công bố kết quả kinh doanh quý 4 năm 2024',
  },
  {
    id: 'event-005',
    title: 'Công bố GDP Q4 Việt Nam',
    type: 'economic',
    date: daysFromNow(10),
    time: '09:00',
    impact: 'high',
    relatedSymbols: [],
    description: 'Tổng cục Thống kê công bố số liệu GDP quý 4',
  },
  {
    id: 'event-006',
    title: 'IPO Công ty Cổ phần ABC',
    type: 'ipo',
    date: daysFromNow(12),
    impact: 'medium',
    relatedSymbols: [],
    description: 'Ngày đầu tiên giao dịch cổ phiếu ABC',
  },
  {
    id: 'event-007',
    title: 'KQKD Q4/2024 - TCB',
    type: 'earnings',
    date: daysFromNow(14),
    time: '17:00',
    impact: 'high',
    relatedSymbols: ['TCB'],
    description: 'Công bố kết quả kinh doanh quý 4 năm 2024',
  },
  {
    id: 'event-008',
    title: 'Trả cổ tức HPG - 500đ/cp',
    type: 'dividend',
    date: daysFromNow(15),
    impact: 'medium',
    relatedSymbols: ['HPG'],
    description: 'Ngày thanh toán cổ tức tiền mặt',
  },
  {
    id: 'event-009',
    title: 'Công bố CPI tháng 1/2025',
    type: 'economic',
    date: daysFromNow(18),
    time: '08:00',
    impact: 'medium',
    relatedSymbols: [],
    description: 'Chỉ số giá tiêu dùng tháng 1',
  },
  {
    id: 'event-010',
    title: 'KQKD Q4/2024 - MWG',
    type: 'earnings',
    date: daysFromNow(20),
    time: '18:00',
    impact: 'high',
    relatedSymbols: ['MWG'],
    description: 'Công bố kết quả kinh doanh quý 4 năm 2024',
  },
  {
    id: 'event-011',
    title: 'IPO Ngân hàng XYZ',
    type: 'ipo',
    date: daysFromNow(22),
    impact: 'high',
    relatedSymbols: [],
    description: 'IPO lớn nhất trong lĩnh vực ngân hàng năm 2025',
  },
  {
    id: 'event-012',
    title: 'Trả cổ tức VNM - 2,000đ/cp',
    type: 'dividend',
    date: daysFromNow(25),
    impact: 'medium',
    relatedSymbols: ['VNM'],
    description: 'Ngày thanh toán cổ tức tiền mặt đợt 2',
  },
  {
    id: 'event-013',
    title: 'Họp ECB tháng 2/2025',
    type: 'economic',
    date: daysFromNow(28),
    time: '20:00',
    impact: 'medium',
    relatedSymbols: [],
    description: 'Cuộc họp chính sách tiền tệ của ECB',
  },
  {
    id: 'event-014',
    title: 'KQKD Q4/2024 - VIC',
    type: 'earnings',
    date: daysFromNow(30),
    time: '17:00',
    impact: 'high',
    relatedSymbols: ['VIC', 'VHM'],
    description: 'Công bố kết quả kinh doanh quý 4 năm 2024',
  },
  {
    id: 'event-015',
    title: 'Công bố PMI tháng 2/2025',
    type: 'economic',
    date: daysFromNow(35),
    time: '09:00',
    impact: 'low',
    relatedSymbols: [],
    description: 'Chỉ số nhà quản trị mua hàng tháng 2',
  },
]
